### ISSUE TITLE
mmal : No data recived from sensor

### ISSUE THREAD

**Issue by miteeek** [ivmech/ivport-v2#5]
Hi, 

i have just bought from you an ivport-v2 and I have a problem with one of my camera. I would like to use standard Rpi camera and NOIR Rpi camera. Both are V2 of course. Both have same sensor ( sony IMX219 ) and the only on difference, as we can read on official Rpi site (https://www.raspberrypi.org/products/pi-noir-camera-v2/) is that, NOIR have no infrared filter which is obvious. 

After whole install I recived 0 errors at all but when I ran test_ivport.py, I got an image from "normal" camera and error from second one "mmal :No data recived from sensor. Check all connections, including the Sunny one on the camera board".

After that I checked my NOIR camera and it works fine.

Can you help me with this problem? I have no idea at this moment how to solve this. I think I checked everything and seems to be fine. Just no data. 

I hope there is a way to make it work in other way this multiplexer is just useless for me.

Edit

I have tested multiplexer just with one camera connected. If camera was connected to CAM1 there was no problem at all either for "normal" or noir camera. after i2cdetect -y 1 command i got 0x10 0x64 and 0x70

But if I connect either normal or noir camera to CAM2 and type command i2cdetect -y 1 i get only 0x70 and I am not able to take a still picture.
I am getting this error
`mmal: Cannot read cameara info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly`

**Comment by CitizenDan** [comment]
How did you solve it I’m in the same position
